# Generated by Django 4.1.7 on 2023-03-15 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlyTrucks', '0003_rename_heading_post_año_de_fabricacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Contacto',
            new_name='Precio',
        ),
    ]
