# Generated by Django 4.1.7 on 2023-03-18 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlyTrucks', '0004_rename_contacto_post_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concesionaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_del_Consesionario', models.CharField(max_length=30)),
                ('Direccion_del_Consesionario', models.CharField(max_length=80)),
                ('Horarios_de_Atencion', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Remolques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Modelo_de_su_Acoplado', models.CharField(max_length=30)),
                ('Marca_de_su_Acoplado', models.CharField(max_length=80)),
                ('Año_de_Fabricacion', models.CharField(max_length=15)),
                ('Descripcion', models.CharField(max_length=120)),
                ('Precio', models.CharField(max_length=10)),
            ],
        ),
    ]
